eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: dfss-slave-2
server:
  port:  8012

rabbitmq:
  hostName:  localhost

master:
  ipAddress: http://localhost:8001         
