eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: dfss-slave-1
server:
  port:  8011   

rabbitmq:
  hostName:  localhost         
